export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";
export const UPDATE_PRODUCT_QTY_IN_CART = "UPDATE_PRODUCT_QTY_IN_CART";
export const SELECT_CURRENT_CURRENCY = "SELECT_CURRENT_CURRENCY";
